run:
  go: "1.21"
linters:
  enable:
    - forcetypeassert
issues:
  exclude:
    - .regActualCurrent. is unused
    - "`routeLogger` is unused"
linters-settings:
  staticcheck:
    checks:
      - "-SA1019"
