issues:
  exclude:
  - "func `..Wallbe..showIO` is unused"
  - "func `..Wallbe..showIOs` is unused"
  - .regActualCurrent. is unused
  - .regOverchargeProtect. is unused
  - .regReset. is unused
  - "`routeLogger` is unused"
