name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.3'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install tools
      run: make install

    - name: Assets & UI
      run: make npm

    - name: Porcelain
      run: |
        test -z "$(git status --porcelain)" || (git status; git diff; false)
