name: Default

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  check-go:
    name: Test & Lint Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erezrokah/setup-go@feat/add_cache_prefix
        with:
          go-version: ^1.20
          cache-key-prefix: clean-cache-
        id: go

      - name: Install tools
        run: make install

      - name: Assets
        run: make assets

      - name: Docs
        run: make docs

      - name: Toml
        run: make toml

      - name: Porcelain
        run: make porcelain

      - name: Test
        run: mkdir dist && touch dist/empty && make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m

  check-ui:
    name: Test & Lint UI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install tools
        run: make install-ui

      - name: Lint
        run: make lint-ui

      - name: Test
        run: make test-ui

      - name: Porcelain
        run: make porcelain

  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - uses: erezrokah/setup-go@feat/add_cache_prefix
        with:
          go-version: ^1.20
          cache-key-prefix: test-cache-
        id: go

      - uses: actions/checkout@v3

      - name: Install UI
        run: make install-ui

      - name: Build UI
        run: make ui

      - name: Build Go
        run: make build

      - name: Install browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
