name: Default

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  check-go:
    name: Test & Lint Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Prepare
        run: mkdir dist && touch dist/empty

      - name: Install tools
        run: make install

      - name: Assets
        run: make assets

      - name: Docs
        run: make docs

      - name: Toml
        run: make toml

      - name: Porcelain
        run: make porcelain

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m

  check-ui:
    name: Test & Lint UI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install tools
        run: make install-ui

      - name: Lint
        run: make lint-ui

      - name: Test
        run: make test-ui

      - name: Porcelain
        run: |
          test -z "$(git status --porcelain)" || (git status; git diff; false)

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Install UI
        run: make install-ui

      - name: Build UI
        run: make ui

      - name: Build
        run: make build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: evcc-binary
          path: ./evcc

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: evcc-binary

      - name: Display structure of downloaded files
        run: ls -R

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install npm
        run: make install-ui

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
