name: Docker

on:
  # push:
  #   branches:
  #   - actions
  workflow_run:
    workflows:
    - Build
    types:
    - completed
    branches:
    - actions

jobs:

  build:
    name: Docker
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | sudo bash -s -- -b $GOPATH/bin v0.5.1

    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

    - name: Build
      run: make publish-latest
