name: Validate Schema

on:
  push:
    paths:
    - "*.yaml"
  pull_request:
    paths:
    - "*.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nwisbeta/validate-yaml-schema@v1.0.3
      with:
        yamlSchemasJson: |
          {
              "file:///schema.json": ["evcc.dist.yaml"],
          }
